# User controller used beside the controller generated by devise
class UsersController < ApplicationController
  include W000thentication

  # Auth by token before show, the informations depends on the user rights
  before_action :w000thenticate_admin!
  before_action :set_user, only: [:show, :wall]

  # GET /users
  def index
    respond_to do |format|
      format.html do
        fail ActionController::RoutingError.new(UsersController, 'Not Found')
      end
      format.json do
        @users = User.all
      end
    end
  end

  # GET /users/:user_pseudo
  def show
  end

  private

  def set_user
    return unless user_params[:user_pseudo]
    @user = User.find_by(pseudo: user_params[:user_pseudo])
  end

  def user_params
    params.permit(:user_pseudo)
  end
end
